# -*- coding: utf-8 -*-
"""dadosaleatorios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J4g2eoCuPhYxSyOIc20CV_8v4KRgZAmy
"""

import numpy as np
from matplotlib import pyplot as plt

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys>195),facecolor='g', alpha=0.6)

plt.title("Visualização de dados gerados de forma randômica")
plt.show()